GET http://localhost:3000/api/v1/articles

###

GET http://localhost:3000/api/v1/articles?take=10

###

GET http://localhost:3000/api/v1/articles?take=10&skip=10

###

GET http://localhost:3000/api/v1/articles?skip=10


###

GET http://localhost:3000/api/v1/articles/3


###

POST http://localhost:3000/api/v1/articles
Content-Type: application/json

{
    "titre" : "We are the champions",
    "image" : "CHAMPIONS.png",
    "contenu" : "Hala Madrid ! ",
    "authorId" : 5,
    "categorieArray" : [
        7
    ]
}


###

DELETE http://localhost:3000/api/v1/articles/2
